version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    command: ./myApp
    environment:
      #      connection: postgres://postgres:duman070601@host.docker.internal:5432/snippetbox?sslmode=disable
#      connection: postgres://postgres:duman070601@127.0.0.1:5432/snippetbox
#      GOOGLE_CLIENT_ID: 904821786927-2c4giicnosn3reko40pqarq02rc1bii5.apps.googleusercontent.com
#      GOOGLE_CLIENT_SECRET: luLkBao_Zpw0JewdZMQk8-j9
#      CALLBACK_URL: https://localhost:4001/auth/google/callback
    restart: always
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: duman070601
      POSTGRES_DB: snippetbox
    restart: always

volumes:
  postgres-data: