version: "3"
services:
  news:
    build:
      dockerfile: Dockerfile
      context: ./news
    ports:
      - "4011:4011"
    command: ./myApp
    restart: always
    depends_on:
      - news_db

  news_db:
    image: postgres
    container_name: postgresdb_container
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: duman070601
      POSTGRES_DB: snippetbox_news
    restart: always

#  uesrs_db:
#    image: postgres
#    container_name: postgres_container
#    ports:
#      - 5432:5432
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_PASSWORD: duman070601
#      POSTGRES_DB: snippetbox_users
#    restart: always

volumes:
  postgres-data: